version: 0.2

phases:

  pre_build:
    commands:
       - git config --global --add safe.directory /home/developer/flutter
       
  build:
    commands:
       - echo 'Execution folder:'
       - pwd
       - flutter clean
       - flutter build apk
       
artifacts:
  files:
     - build/app/outputs/flutter-apk/app-release.apk
  discard-paths: yes