version: 0.2

phases:

  pre_build:
    commands:
       - git config --global --add safe.directory /home/developer/flutter
       
  build:
    commands:
       - echo 'Execution folder:'
       - pwd
       - flutter clean
       - flutter build apk
       
  post_build:
    commands:
       - echo 'Looking for the apk'
       - test -f /codebuild/output/src338176332/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/test_flutter/build/app/outputs/flutter-apk/app-release.apk echo "$FILE exists."
       
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths