version: 0.2

phases:

  pre_build:
    commands:
       - git config --global --add safe.directory /home/developer/flutter
       - java -version
       - flutter doctor
       
  build:
    commands:
       - echo 'Execution folder:'
       - pwd
       - flutter clean
       - flutter build apk
       
  #post_build:
    #commands:
      # - command
      # - command

#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths